sudo: required
services: 
  - docker

before_install:
  - docker build -t nichu/docker-react -f Dockerfile.dev .

script: # -- --coverage added to go out of rnp run test command (by default waits for user input)
  - docker run nichu/docker-react  npm run test -- --coverage
